spring.application.name=Student Portal
spring.data.mongodb.database=student_portal
spring.data.mongodb.uri=mongodb://localhost:27017/student_portal

server.port=8080
spring.main.allow-bean-definition-overriding=true

spring.mail.host=smtp.mail.ru
spring.mail.port=587
spring.mail.username=akzhigitnurkeldi@inbox.ru
spring.mail.password=1ivJhkD8jWZBPFIsj75V
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.mail.ru